[beans]
prefix = 'beans-'
id_length = 4
default_status = 'open'

[[statuses]]
name = 'open'
color = 'green'

[[statuses]]
name = 'in-progress'
color = 'yellow'

[[statuses]]
name = 'done'
color = 'gray'
archive = true

[[types]]
name = 'task'
color = 'blue'

[[types]]
name = 'feature'
color = 'green'

[[types]]
name = 'bug'
color = 'red'

[[types]]
name = 'epic'
color = 'purple'
